# Auto-generated by CloudCrew AI
# Do not edit manually

project_name = "production-three-tier"
environment = "production"
az_count = 2
region = "us-east-1"
vpc_cidr = "172.16.0.0/16"
public_subnet_cidrs = ["172.16.1.0/24", "172.16.2.0/24"]
private_subnet_cidrs = ["172.16.11.0/24", "172.16.12.0/24"]
database_subnet_cidrs = ["172.16.21.0/24", "172.16.22.0/24"]
